// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDelg5zv2v0UDmZghT5senGnmpL-XnN4',
    appId: '1:349458851809:web:ec9185dd589744e6c594a0',
    messagingSenderId: '349458851809',
    projectId: 'society-gate-39b69',
    authDomain: 'society-gate-39b69.firebaseapp.com',
    storageBucket: 'society-gate-39b69.firebasestorage.app',
    measurementId: 'G-60PLYGNGDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBBZaAhS9E0XMcedyk_fyyCc4JqEbvyM',
    appId: '1:349458851809:android:fa08d07a09ddcb71c594a0',
    messagingSenderId: '349458851809',
    projectId: 'society-gate-39b69',
    storageBucket: 'society-gate-39b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bim5wfrAeJxtiI711F-Gqada-IxPctQ',
    appId: '1:349458851809:ios:f09abcaba5dee8f3c594a0',
    messagingSenderId: '349458851809',
    projectId: 'society-gate-39b69',
    storageBucket: 'society-gate-39b69.firebasestorage.app',
    iosBundleId: 'com.example.mySociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0bim5wfrAeJxtiI711F-Gqada-IxPctQ',
    appId: '1:349458851809:ios:f09abcaba5dee8f3c594a0',
    messagingSenderId: '349458851809',
    projectId: 'society-gate-39b69',
    storageBucket: 'society-gate-39b69.firebasestorage.app',
    iosBundleId: 'com.example.mySociety',
  );
}
